// <auto-generated />
namespace BreadSpread.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Checking1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Checking1));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091636505_Checking1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
